Repository ModelEngine-Group/pipeline, pull requests merged in 2025-07, with the labels that each got.

#32 [appbuilder] 修复拷贝应用头像时报错
  independent/x86/framework/fit/java/build.sh
Labels: type: bug

#39 [app-engine] adpat macOS
  .gitignore
  README.md
  independent/x86/build.sh
  independent/x86/env.sh
  independent/x86/framework/fit/fit-java/build.sh
  independent/x86/framework/fit/java/build.sh
  independent/x86/modify.sh
  independent/x86/pack/docker-compose.yml
  independent/x86/pack/install_x86.bat
  independent/x86/pack/shell/initDB.sh
  independent/x86/pack/uninstall_x86.bat
  independent/x86/pack/upgrade_x86.bat
Labels: type: enhancement

#42 修改nginx配置，使得/api/jober/前缀接口支持websocket
  independent/x86/frontend/nginx.conf
Labels: type: task

#43 [app-builder] 增加表单源码编译逻辑
  independent/x86/framework/fit/java/build.sh
  independent/x86/frontend/build.sh
Labels: type: task
